config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  resources :mutants

  resources :teams do
    resources :tasks, :only => [:index]
    resources :mutants, :only => [:index]
  end

  root :to => 'teams#index'
end

app/models/mutant.rb
class Mutant < ActiveRecord::Base
  belongs_to :team

  validates_presence_of :name
  validates_presence_of :country
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :team

  enum status: [:active , :archived]

  validates_presence_of :name
  validates_presence_of :status

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :tasks, :dependent => :destroy
  has_many :mutants

  accepts_nested_attributes_for :tasks, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :mutants, :reject_if => :all_blank, :allow_destroy => true

  validates_presence_of :name
  validates_presence_of :description


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mutants_controller.rb
class MutantsController < ApplicationController
  before_action :set_mutant, only: [:show, :edit, :update, :destroy]
  before_action :set_team, only: [:index]

  # GET /mutants
  # GET /mutants.json
  def index
    @mutants = @team.nil? ? Mutant.all : @team.mutants
  end

  # GET /mutants/1
  # GET /mutants/1.json
  def show
  end

  # GET /mutants/new
  def new
    @mutant = Mutant.new
  end

  # GET /mutants/1/edit
  def edit
  end

  # POST /mutants
  # POST /mutants.json
  def create
    @mutant = Mutant.new(mutant_params)

    respond_to do |format|
      if @mutant.save
        format.html { redirect_to @mutant, notice: 'Mutant was successfully created.' }
        format.json { render :show, status: :created, location: @mutant }
      else
        format.html { render :new }
        format.json { render json: @mutant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mutants/1
  # PATCH/PUT /mutants/1.json
  def update
    respond_to do |format|
      if @mutant.update(mutant_params)
        format.html { redirect_to @mutant, notice: 'Mutant was successfully updated.' }
        format.json { render :show, status: :ok, location: @mutant }
      else
        format.html { render :edit }
        format.json { render json: @mutant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mutants/1
  # DELETE /mutants/1.json
  def destroy
    @mutant.destroy
    respond_to do |format|
      format.html { redirect_to mutants_url, notice: 'Mutant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mutant
      @mutant = Mutant.find(params[:id])
    end

    def set_team
      @team =
        if params[:team_id].present?
          begin
            Team.find(params[:team_id])
          rescue ActiveRecord::RecordNotFound
            @team = nil
          end
        else
          nil
        end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mutant_params
      params.require(:mutant).permit(:name, :country)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_team, only: [:index]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @team.nil? ? Task.all : @team.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_team
      @team =
          if params[:team_id].present?
            begin
              Team.find(params[:team_id])
            rescue ActiveRecord::RecordNotFound
              @team = nil
            end
          else
            nil
          end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :status)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(
        :name, :description,
        tasks_attributes: [:id, :name, :status, :_destroy],
        mutants_attributes: [:id, :name, :country, :_destroy]
      )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def has_many_link(instance, association, style = 'warning')
    team_tasks_label = []
    team_tasks_label << t(".#{association}", :default => t("helpers.links.#{association}"))
    team_tasks_label << '&nbsp;'
    team_tasks_label << content_tag(:span, instance.send(association).count, :class => 'badge')
    link_to(team_tasks_label.join.html_safe, url_for([instance, association]), :class => "btn btn-#{style} btn-xs")
  end


end

app/helpers/mutants_helper.rb
module MutantsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "SuseChallenge"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") SuseChallenge
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to Team.model_name.human(:count => :many), teams_path
            %li= link_to Task.model_name.human(:count => :many), tasks_path
            %li= link_to Mutant.model_name.human(:count => :many), mutants_path
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li= link_to Team.model_name.human(:count => :many), teams_path
              %li= link_to Task.model_name.human(:count => :many), tasks_path
              %li= link_to Mutant.model_name.human(:count => :many), mutants_path
      %footer
        %p &copy; Company 2014

app/views/mutants/_form.html.haml
= simple_form_for @mutant, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :country, :as => :country
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), mutants_path, :class => 'btn btn-default'

app/views/mutants/edit.html.haml
- model_class = Mutant
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/mutants/index.html.haml
- model_class = Mutant
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:country)
      %th= model_class.human_attribute_name(:team_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @mutants.each do |mutant|
      %tr
        %td= link_to mutant.id, mutant_path(mutant)
        %td= mutant.name
        %td= mutant.country
        %td= mutant.team_id
        %td=l mutant.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_mutant_path(mutant), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), mutant_path(mutant), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_mutant_path, :class => 'btn btn-primary'
= link_to t('.back', :default => t("helpers.links.back")), :back, :class => 'btn btn-default'

app/views/mutants/new.html.haml
- model_class = Mutant
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/mutants/show.html.haml
- model_class = Mutant
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @mutant.name
%p
  %strong= model_class.human_attribute_name(:country) + ':'
  %br
  = @mutant.country
%p
  %strong= model_class.human_attribute_name(:team_id) + ':'
  %br
  = @mutant.team_id


= link_to t('.back', :default => t("helpers.links.back")), mutants_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_mutant_path(@mutant), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), mutant_path(@mutant), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/tasks/_form.html.haml
= simple_form_for @task, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :status, :collection => Task.statuses.keys, include_blank: false
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), tasks_path, :class => 'btn btn-default'

app/views/tasks/edit.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tasks/index.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:status)
      %th= model_class.human_attribute_name(:team_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @tasks.each do |task|
      %tr
        %td= link_to task.id, task_path(task)
        %td= task.name
        %td= task.status
        %td= task.team_id
        %td=l task.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(task), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(task), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_task_path, :class => 'btn btn-primary'
= link_to t('.back', :default => t("helpers.links.back")), :back, :class => 'btn btn-default'

app/views/tasks/new.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tasks/show.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @task.name
%p
  %strong= model_class.human_attribute_name(:status) + ':'
  %br
  = @task.status
%p
  %strong= model_class.human_attribute_name(:team_id) + ':'
  %br
  = @task.team_id


= link_to t('.back', :default => t("helpers.links.back")), tasks_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(@task), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(@task), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'